// <auto-generated />
using System;
using LadgerAPI_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LadgerAPI_2.Migrations
{
    [DbContext(typeof(LadgerAPI_2Context))]
    [Migration("20240805140732_01")]
    partial class _01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LadgerAPI_2.Models.Ladger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ladger");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LadgerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LadgerId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LadgerId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LadgerId");

                    b.HasIndex("TransactionId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.Transaction", b =>
                {
                    b.HasOne("LadgerAPI_2.Models.Ladger", "Ladger")
                        .WithMany("Transactions")
                        .HasForeignKey("LadgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ladger");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.User", b =>
                {
                    b.HasOne("LadgerAPI_2.Models.Ladger", null)
                        .WithMany("Users")
                        .HasForeignKey("LadgerId");

                    b.HasOne("LadgerAPI_2.Models.Transaction", null)
                        .WithMany("PaidBy")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.Ladger", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LadgerAPI_2.Models.Transaction", b =>
                {
                    b.Navigation("PaidBy");
                });
#pragma warning restore 612, 618
        }
    }
}
